name: E2E Integration Test

on: 
  push:
  pull_request:


permissions:
  contents: read

jobs:

  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Backend setup
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      working-directory: ./backend
      
    - name: Run server
      run: fastapi run &
      working-directory: ./backend

    # Run frontend
    - name: Install pnpm
      run: |
        npm install -g pnpm
        pnpm config set side-effects-cache false 
        pnpm --allow-build=cypress add --save-dev cypress
        pnpm i
      working-directory: ./frontend

    - name: Install dependencies
      uses: cypress-io/github-action@v6
      with: 
        working-directory: ./frontend
        runTests: false

    - name: Set env
      run: echo "NEXT_PUBLIC_BACKEND_URL=http://localhost:8000" >> $GITHUB_ENV
    
    - name: Cypress test
      uses: cypress-io/github-action@v6
      with:
        install: false
        build: pnpm build
        start: pnpm test-run
        browser: chrome
        spec: cypress/e2e/app.cy.ts
        working-directory: ./frontend
        wait-on: http://localhost:3000
        
          



