name: E2E Integration Test

on: 
  push:
  pull_request:


permissions:
  contents: read

jobs:

  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Backend setup
    - name: Setup Backend
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - run: |
          pip install -r requirements.txt
      working-directory: ./backend
      
    - name: Run server
      run: fastapi run &
      working-directory: ./backend

    # Run frontend
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
        
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: "pnpm"
        cache-dependency-path: ./frontend/pnpm-lock.yaml

    - name: Setup Cypress
      uses: cypress-io/github-action@v6
      with: 
        working-directory: ./frontend
        runTests: false
    - uses: actions/cache@v4
      with:
        path: ./frontend/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
        working-directory: ./frontend
          
    - name: Set env
      run: echo "NEXT_PUBLIC_BACKEND_URL=http://localhost:8000" >> $GITHUB_ENV
    
    - name: Cypress test
      uses: cypress-io/github-action@v6
      with:
        install: false
        build: pnpm build
        start: pnpm start
        browser: chrome
        spec: cypress/e2e/app.cy.ts
        working-directory: ./frontend
        wait-on: http://localhost:3000
          
        
          



